# Generated by Django 5.2 on 2025-04-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='todo',
            new_name='task',
        ),
    ]
